In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
import os

# Get the current directory
current_dir = os.getcwd()

# Get the parent directory
parent_dir = os.path.dirname(current_dir)

# Check if the current directory is already the parent directory
if current_dir != '/Users/macoftraopia/Documents/GitHub/RGCN-Explainer':
    # Set the parent directory as the current directory
    os.chdir(parent_dir)
!pwd

/Users/macoftraopia/Documents/GitHub/RGCN-Explainer

In [4]:
name = 'aifb'

In [65]:
df = pd.read_csv(f'chk/{name}_chk/Important_baseline_{name}_results_ones.csv')
df.set_index('node_idx', inplace=True)
df['tot'] = df.sum(axis=1) - df['label'] 
df.head()

,label,abstract,address,author,booktitle,carriedOutBy,carriesOut,chapter,dealtWithIn,edition,...,worksAtProject,year,type.1,type.2,range,subClassOf,allValuesFrom,inverseOf,onProperty,tot
node_idx,,,,,,,,,,,,,,,,,,,,,
5678,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
5724,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0
5699,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0
5688,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0
5702,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,5.0

In [67]:
gb = df.groupby('label')    
for i in np.unique(df['label']):
    exec(f'group_{i} = gb.get_group(i)')
    exec(f'group_rel_{i} = group_{i}.iloc[:,1:].div(group_{i}.tot, axis=0)')
    exec(f'group_rel_{i} = group_rel_{i}.drop(columns=["tot"])')
    exec(f'group_max_{i} = group_rel_{i}.idxmax(axis=1)')

#group_rel_0
print('group_max_0:', group_max_0.value_counts(),
      '\n group_max_1:', group_max_1.value_counts(),#,
         '\n group_max_2:', group_max_2.value_counts(),
         '\n group_max_3:', group_max_3.value_counts())

group_max_0: fax    14
dtype: int64
 group_max_1: homepage    2
photo       2
dtype: int64
 group_max_2: phone    11
dtype: int64
 group_max_3: type    6
dtype: int64